services:
  backend:
    build: ./backend
    # (opcional) mejor sin container_name para evitar choques
    # container_name: patrol_backend
    env_file: .env
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - patrol_net

networks:
  patrol_net:
    external: true
